# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sara Sithi-Amnuai
description: >- # this means to ignore newlines until "baseurl:"
  I’m deeply interested in diverse user perspectives and create experiences and tools that help artists freely express themselves.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sarasithi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.markdown
  - clouds.markdown
  - media.markdown
  - about.markdown

minima:
  social_links:
    linkedin: "sara-sithi-amnuai-050509104"